### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by maksutovnurda** [MichalPlatko/EduPage-Anal-Penetration#1]
Uncaught TypeError: Cannot read property 'children' of undefined
    at <anonymous>:7:32
    at Array.forEach (<anonymous>)
    at ojebovak (<anonymous>:4:35)
    at <anonymous>:1:1

**Comment by MichalPlatko** [comment]
Thanks for pointing out,that was copied code from existing code that was working only on specific so i got rid of if just so it doesnt break function
